baseURL: "https://notfirefox.dev"
title: "Snowblog"
theme: "wondermod"

params:
  env: prodcution
  defaultTheme: auto
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowFullTextInRSS: true

  profileMode:
    enabled: true
    title: Snowblog
    subtitle: My blog posts about security
    button:
      - name: About
        url: about
      - name: Donate
        url: donate

  socialIcons:
    - name: github
      url: "https://github.com/notfirefox"
    - name: matrix
      url: "https://matrix.to/#/@notfirefox:matrix.org"
    - name: rss
      url: /index.xml

  fuseOpts:
      isCaseSensitive: false
      shouldSort: true
      location: 0
      distance: 1000
      threshold: 0.4
      minMatchCharLength: 0
      keys: ["title", "permalink", "summary", "content"]

outputs:
  home:
    - HTML
    - RSS
    - JSON

menu:
  main:
    - identifier: Categories
      name: Categories
      url: /posts/
      weight: 10
    - identifier: Tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: Search
      name: Search
      url: /search/
      weight: 30

